<?php
declare(strict_types=1);require dirname(__DIR__,2).'/src/bootstrap.php';
use Sedema\Authorization;use Sedema\Csrf;use Sedema\Logistics\LogisticsContext;use Sedema\Logistics\LogisticsPage;
$c=LogisticsContext::boot();$user=$c['user'];$repo=$c['repository'];$service=$c['service'];$id=max(0,(int)($_GET['id']??0));$d=$repo->dispatch($id);if(!$d){http_response_code(404);exit('Despacho no encontrado.');}$items=$repo->dispatchItems($id);$history=$repo->history($id);$next=['EN_ESPERA'=>['EN_PREPARACION'=>'Iniciar preparación'],'EN_PREPARACION'=>['EN_RUTA'=>'Iniciar ruta'],'EN_RUTA'=>['ENTREGADO'=>'Confirmar entrega','DEVUELTO'=>'Registrar devolución'],'ENTREGADO'=>['DEVUELTO'=>'Registrar devolución'],'DEVUELTO'=>[]][(string)$d['estado']]??[];LogisticsPage::begin('Despacho #'.$id,'overview',$user);?>
<section class="inventory-heading compact-heading"><div><p class="section-kicker">Seguimiento operativo</p><h2>Despacho #<?=$id?></h2><p>Pedido #<?=(int)$d['idPedido']?> · <?=e(trim((string)$d['clienteNombre']))?></p></div><div class="inventory-actions"><a class="button button-secondary" target="_blank" href="route-sheet.php?id=<?=$id?>"><?=LogisticsPage::icon('print')?> Hoja de ruta</a><a class="button button-secondary" target="_blank" href="remito.php?id=<?=$id?>"><?=LogisticsPage::icon('print')?> Remito</a></div></section>
<section class="logistics-detail-grid"><article class="inventory-panel logistics-card"><h3>Entrega</h3><dl><div><dt>Estado</dt><dd><span class="logistics-status state-<?=strtolower((string)$d['estado'])?>"><?=e($service->stateLabel((string)$d['estado']))?></span></dd></div><div><dt>Programada</dt><dd><?=e(date('d/m/Y H:i',strtotime((string)$d['fechaHoraProgramada'])))?></dd></div><div><dt>Modalidad</dt><dd><?=$d['modalidad']==='ENTREGA_DOMICILIO'?'Entrega a domicilio':'Retiro en corralón'?></dd></div><div><dt>Destino</dt><dd><?=e((string)$d['destino'])?></dd></div></dl></article><article class="inventory-panel logistics-card"><h3>Recursos</h3><dl><div><dt>Depósito</dt><dd><?=e((string)$d['warehouseName'])?></dd></div><div><dt>Vehículo</dt><dd><?=e($d['matricula']?((string)$d['matricula'].' · '.$d['modelo']):'No requerido')?></dd></div><div><dt>Remito</dt><dd><?=e((string)$d['numeroRemito'])?></dd></div><div><dt>Hoja de ruta</dt><dd><?=e((string)$d['hojaRuta'])?></dd></div></dl></article></section>
<section class="inventory-panel"><div class="panel-title-row"><div><h3>Productos asignados</h3><p>El egreso se asienta al pasar a En ruta.</p></div></div><div class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th>Código</th><th>Producto</th><th>Cantidad</th><th>Pendiente actual</th></tr></thead><tbody><?php foreach($items as $i):?><tr><td><?=e((string)$i['code'])?></td><td><strong><?=e((string)$i['productName'])?></strong></td><td><?=e($service->quantity((float)$i['cantidadADespachar']))?> <?=e((string)$i['symbol'])?></td><td><?=e($service->quantity((float)$i['cantidadPendiente']))?> <?=e((string)$i['symbol'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php if(Authorization::can($user,'logistics.dispatch')&&$next):?><section class="inventory-panel logistics-transition"><div><h3>Actualizar estado</h3><p>La operación queda registrada con usuario y fecha.</p></div><?php foreach($next as $state=>$label):?><form method="post" action="action.php"><input type="hidden" name="csrf_token" value="<?=e(Csrf::token())?>"><input type="hidden" name="action" value="transition"><input type="hidden" name="idDespacho" value="<?=$id?>"><input type="hidden" name="estado" value="<?=$state?>"><div class="field"><label for="note-<?=$state?>">Observación</label><input id="note-<?=$state?>" name="observaciones" maxlength="500" placeholder="Detalle opcional"></div><button class="button <?=$state==='DEVUELTO'?'button-secondary':'button-primary'?>" type="submit" data-confirm-state="<?=$state?>"><?=$label?></button></form><?php endforeach;?></section><?php endif;?>
<section class="inventory-panel"><div class="panel-title-row"><div><h3>Trazabilidad</h3><p>Historial de estados del despacho.</p></div></div><div class="timeline"><?php foreach($history as $h):?><article><span></span><div><strong><?=e($service->stateLabel((string)$h['estadoNuevo']))?></strong><p><?=e((string)($h['observaciones']?:'Sin observaciones'))?></p><small><?=e(date('d/m/Y H:i',strtotime((string)$h['creadoEn'])))?> · <?=e((string)$h['actorName'])?></small></div></article><?php endforeach;?></div></section>
<?php LogisticsPage::end();
