<?php
declare(strict_types=1);require dirname(__DIR__,2).'/src/bootstrap.php';
use Sedema\Authorization;use Sedema\Csrf;use Sedema\Logistics\LogisticsContext;use Sedema\Logistics\LogisticsPage;
$c=LogisticsContext::boot();$user=$c['user'];Authorization::require($user,'logistics.manage');$repo=$c['repository'];$service=$c['service'];$orders=$repo->orders();$orderId=max(0,(int)($_GET['order']??0));$items=$orderId>0?$repo->orderItems($orderId):[];$warehouses=$repo->warehouses();$vehicles=$repo->vehicles();LogisticsPage::begin('Programar despacho','dispatch',$user);?>
<section class="inventory-heading compact-heading"><div><p class="section-kicker">Nueva operación</p><h2>Programar entrega parcial o total</h2><p>Las cantidades quedan reservadas; el stock se descuenta recién al iniciar la ruta.</p></div><a class="back-button" href="index.php">← Volver</a></section>
<form class="inventory-toolbar logistics-order-picker" method="get"><div class="field compact-field"><label for="order">Pedido</label><select id="order" name="order" required><option value="">Seleccionar pedido</option><?php foreach($orders as $o):?><option value="<?=(int)$o['idPedido']?>" <?=(int)$o['idPedido']===$orderId?'selected':''?>>#<?=(int)$o['idPedido']?> · <?=e(trim((string)$o['clienteNombre']))?> · <?=(int)$o['pendingLines']?> renglones pendientes</option><?php endforeach;?></select></div><button class="button button-filter" type="submit">Cargar productos</button></form>
<?php if($orderId>0):?><form class="inventory-form" method="post" action="action.php"><input type="hidden" name="csrf_token" value="<?=e(Csrf::token())?>"><input type="hidden" name="action" value="schedule"><input type="hidden" name="idPedido" value="<?=$orderId?>"><section class="form-section"><div class="form-section-heading"><span>01</span><div><h3>Datos operativos</h3><p>Origen, modalidad y agenda.</p></div></div><div class="form-grid"><div class="field"><label for="warehouse">Depósito *</label><select id="warehouse" name="idWarehouse" required><?php foreach($warehouses as $w):?><option value="<?=(int)$w['idWarehouse']?>"><?=e((string)$w['name'])?></option><?php endforeach;?></select></div><div class="field"><label for="scheduled">Fecha y hora *</label><input id="scheduled" name="fechaHoraProgramada" type="datetime-local" required></div><div class="field"><label for="mode">Modalidad *</label><select id="mode" name="modalidad" data-logistics-mode required><option value="ENTREGA_DOMICILIO">Entrega a domicilio</option><option value="EN_CORRALON">Retiro en corralón</option></select></div><div class="field" data-vehicle-field><label for="vehicle">Vehículo *</label><select id="vehicle" name="idVehiculo"><option value="">Seleccionar</option><?php foreach($vehicles as $v):?><option value="<?=(int)$v['idVehiculo']?>" <?=$v['estado']!=='DISPONIBLE'?'disabled':''?>><?=e((string)$v['matricula'])?> · <?=e((string)$v['modelo'])?> · <?=e((string)$v['estado'])?></option><?php endforeach;?></select></div><div class="field field-span"><label for="destination">Destino *</label><input id="destination" name="destino" maxlength="255" required placeholder="Domicilio de entrega o sector de retiro"></div><div class="field field-span"><label for="notes">Observaciones</label><textarea id="notes" name="observacionesEntrega" maxlength="1000"></textarea></div></div></section>
<section class="form-section"><div class="form-section-heading"><span>02</span><div><h3>Productos</h3><p>Ingresá cero en los renglones que quedarán para otro despacho.</p></div></div><div class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th>Producto</th><th>Solicitado</th><th>Pendiente</th><th>Reservado</th><th>Disponible</th><th>A despachar</th></tr></thead><tbody><?php foreach($items as $item):$available=max(0,(float)$item['cantidadPendiente']-(float)$item['reservado']);?><tr><td><strong><?=e((string)$item['productName'])?></strong><span class="cell-meta"><?=e((string)$item['code'])?></span></td><td><?=e($service->quantity((float)$item['cantidadSolicitada']))?> <?=e((string)$item['symbol'])?></td><td><?=e($service->quantity((float)$item['cantidadPendiente']))?></td><td><?=e($service->quantity((float)$item['reservado']))?></td><td><strong><?=e($service->quantity($available))?></strong></td><td><input class="quantity-input" type="number" name="quantity[<?=(int)$item['idDetalle']?>]" value="0" min="0" max="<?=$available?>" step="<?=(int)$item['allowsDecimals']===1?'0.001':'1'?>"></td></tr><?php endforeach;?></tbody></table></div><button class="button button-primary button-full" type="submit">Confirmar programación</button></section></form><?php endif;?>
<?php LogisticsPage::end();
