<?php
declare(strict_types=1);require dirname(__DIR__,2).'/src/bootstrap.php';
use Sedema\Authorization;use Sedema\Logistics\LogisticsContext;use Sedema\Logistics\LogisticsPage;
$c=LogisticsContext::boot();$user=$c['user'];$repo=$c['repository'];$service=$c['service'];$state=mb_strtoupper(trim((string)($_GET['state']??'')));if(!in_array($state,['EN_ESPERA','EN_PREPARACION','EN_RUTA','ENTREGADO','DEVUELTO'],true))$state='';$summary=$repo->summary();$dispatches=$repo->dispatches($state);LogisticsPage::begin('Despachos','overview',$user);?>
<section class="inventory-heading"><div><p class="section-kicker">Operación diaria</p><h2>Despachos programados</h2><p>Preparación, salida, entrega y devolución con impacto trazable en stock.</p></div><?php if(Authorization::can($user,'logistics.manage')):?><a class="button button-primary" href="dispatch.php"><?=LogisticsPage::icon('plus')?> Programar despacho</a><?php endif;?></section>
<section class="inventory-stats"><article><div><strong><?=$summary['waiting']?></strong><span>En espera</span></div></article><article><div><strong><?=$summary['preparing']?></strong><span>En preparación</span></div></article><article><div><strong><?=$summary['onRoute']?></strong><span>En ruta</span></div></article><article><div><strong><?=$summary['delivered']?></strong><span>Entregados</span></div></article></section>
<form class="inventory-toolbar" method="get"><div class="field compact-field"><label for="state">Estado</label><select id="state" name="state"><option value="">Todos</option><?php foreach(['EN_ESPERA','EN_PREPARACION','EN_RUTA','ENTREGADO','DEVUELTO'] as $s):?><option value="<?=$s?>" <?=$state===$s?'selected':''?>><?=e($service->stateLabel($s))?></option><?php endforeach;?></select></div><button class="button button-filter" type="submit">Filtrar</button></form>
<section class="inventory-panel"><div class="panel-title-row"><div><h3>Agenda de entregas</h3><p><?=count($dispatches)?> despachos encontrados</p></div></div><?php if(!$dispatches):?><div class="table-empty"><h4>No hay despachos</h4><p>Programá el primero o cambiá el filtro de estado.</p></div><?php else:?><div class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th>Despacho</th><th>Programación</th><th>Cliente / destino</th><th>Origen</th><th>Modalidad</th><th>Estado</th><th></th></tr></thead><tbody><?php foreach($dispatches as $d):?><tr><td><strong>#<?=(int)$d['idDespacho']?></strong><span class="cell-meta">Pedido #<?=(int)$d['idPedido']?> · <?=(int)$d['itemCount']?> renglones</span></td><td><?=e(date('d/m/Y H:i',strtotime((string)$d['fechaHoraProgramada'])))?></td><td><strong><?=e(trim((string)$d['clienteNombre']))?></strong><span class="cell-meta"><?=e((string)$d['destino'])?></span></td><td><?=e((string)$d['warehouseName'])?></td><td><?=($d['modalidad']==='ENTREGA_DOMICILIO'?'Domicilio':'Retiro en corralón')?></td><td><span class="logistics-status state-<?=strtolower((string)$d['estado'])?>"><?=e($service->stateLabel((string)$d['estado']))?></span></td><td class="table-actions"><a href="detail.php?id=<?=(int)$d['idDespacho']?>">Abrir</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php LogisticsPage::end();
