<?php
declare(strict_types=1);
namespace Sedema\Payments;
use Sedema\Csrf;
final class PaymentPage
{
 public static function begin(string $title,string $active,array $user):void{$displayName=trim((string)($user['name']??$user['username']));$initial=mb_strtoupper(mb_substr($displayName,0,1));$photo=trim((string)($user['profile_photo']??''));$exists=$photo!==''&&is_file(BASE_PATH.'/public/'.ltrim($photo,'/'));$photoUrl=$exists?'../'.ltrim($photo,'/'):'';$roles=['ADMINISTRADOR'=>'Administrador','VENDEDOR'=>'Ventas','PROVEEDOR'=>'Proveedores','DEPOSITO'=>'Depósito','LOGISTICA'=>'Logística','CAJA'=>'Caja','ALMACEN'=>'Almacén','FINANZAS'=>'Finanzas','SISTEMAS'=>'Sistemas'];$role=$roles[(string)($user['role']??'')]??(string)($user['role']??'Usuario');$flash=self::pullFlash();?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> | Pagos SEDEMA</title><link rel="stylesheet" href="../assets/css/styles.css"></head><body class="dashboard-page inventory-page payments-page"><div class="dashboard-shell"><aside class="dashboard-sidebar" id="dashboard-sidebar"><div class="sidebar-brand"><div class="logo-crop dashboard-logo"><img src="../assets/img/sedema-logo.png" alt="SEDEMA S.R.L."></div><div><strong>SEDEMA</strong><span>Pagos y cobranzas</span></div></div><nav class="sidebar-nav"><p class="nav-label">Sistema</p><a class="nav-item" href="../dashboard.php"><?=self::icon('home')?><span>Panel principal</span></a><p class="nav-label">Pagos</p><?=self::nav('index.php','payments','Cobros de pedidos',$active)?><?=self::nav('current-account.php','account','Cuenta corriente',$active)?></nav><div class="sidebar-footer"><div class="user-menu" data-user-menu><button class="user-menu-trigger" type="button" data-user-menu-trigger aria-expanded="false"><?php if($exists):?><img class="user-avatar is-photo" src="<?=e($photoUrl)?>" alt="Foto de perfil"><?php else:?><span class="user-avatar"><?=e($initial)?></span><?php endif;?><span class="user-menu-copy"><strong><?=e($displayName)?></strong><span><?=e($role)?></span></span><svg class="user-menu-chevron" viewBox="0 0 24 24"><path d="m7 10 5 5 5-5" fill="none" stroke="currentColor" stroke-width="2"/></svg></button><div class="user-menu-panel" data-user-menu-panel hidden><a class="user-menu-link" href="../profile.php#datos">Mi perfil / Modificar datos</a><a class="user-menu-link" href="../profile.php#foto">Cambiar foto</a><a class="user-menu-link" href="../profile.php#seguridad">Cambiar contraseña</a><div class="user-menu-divider"></div><form class="user-menu-form" method="post" action="../logout.php"><input type="hidden" name="csrf_token" value="<?=e(Csrf::token())?>"><button class="user-menu-logout">Cerrar sesión</button></form></div></div></div></aside><button class="sidebar-backdrop" type="button" data-sidebar-close></button><main class="dashboard-workspace"><header class="dashboard-topbar inventory-topbar"><button class="menu-button" type="button" data-sidebar-open><?=self::icon('menu')?></button><div><p class="topbar-kicker">Pagos y cobranzas</p><h1><?=e($title)?></h1></div></header><div class="dashboard-content inventory-content"><?php if($flash):?><div class="alert <?=$flash['type']==='success'?'alert-success':'alert-error'?> inventory-alert"><span><?=$flash['type']==='success'?'✓':'!'?></span><p><?=e($flash['message'])?></p></div><?php endif;?>
<?php }
 public static function end():void{?></div></main></div><script src="../assets/js/dashboard.js" defer></script></body></html><?php }
 public static function flash(string $type,string $message):void{$_SESSION['payment_flash']=['type'=>$type,'message'=>$message];}
 private static function pullFlash():?array{$f=$_SESSION['payment_flash']??null;unset($_SESSION['payment_flash']);return is_array($f)&&isset($f['type'],$f['message'])?$f:null;}
 private static function nav(string $href,string $key,string $label,string $active):string{$c=$key===$active?'nav-item is-active':'nav-item';return '<a class="'.$c.'" href="'.$href.'">'.self::icon($key).'<span>'.e($label).'</span></a>';}
 public static function icon(string $n):string{$icons=['home'=>'<path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10v10h13V10"/>','menu'=>'<path d="M4 6h16M4 12h16M4 18h16"/>','payments'=>'<path d="M4 6h15a2 2 0 0 1 2 2v11H4a2 2 0 0 1-2-2V6a3 3 0 0 1 3-3h13"/><path d="M16 11h5v4h-5a2 2 0 0 1 0-4Z"/>','account'=>'<path d="M4 5h16v14H4z"/><path d="M8 9h8M8 13h5"/>'];return '<svg viewBox="0 0 24 24" aria-hidden="true">'.($icons[$n]??$icons['payments']).'</svg>';}
}
