<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/src/bootstrap.php';
use Sedema\{Authorization,Csrf};
use Sedema\Suppliers\{SupplierContext,SupplierPage};
$c=SupplierContext::boot(); $u=$c['user']; $id=(int)($_GET['id']??0); $r=$c['repository'];
$order=$r->order($id); if(!$order){http_response_code(404);exit('Remito inexistente.');}
$lines=$r->lines($id); $receipts=$r->receptions($id); $warehouses=$r->warehouses();
$open=!in_array($order['estado'],['CANCELADA','RECEPCION_TOTAL'],true);
SupplierPage::begin('Remito '.$order['numeroRemito'],'overview',$u);
?>
<section class="inventory-heading compact-heading"><div><p class="section-kicker">Compra #<?= $id ?></p><h2>Remito <?= e((string)$order['numeroRemito']) ?></h2><p><?= e((string)$order['razonSocial']) ?> · <?= e((string)$order['fechaEmision']) ?> · <?= e((string)$order['estado']) ?></p></div><a class="back-button" href="index.php">← Volver</a></section>
<section class="inventory-panel"><div class="panel-title-row"><div><h3>Materiales y avance</h3></div></div><div class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th>Producto</th><th>Solicitado</th><th>Recibido</th><th>Pendiente</th><th>Precio unitario</th></tr></thead><tbody><?php foreach($lines as $line): ?><tr><td><?= e((string)$line['code'].' · '.$line['name']) ?></td><td><?= e((string)$line['cantidadSolicitada']) ?> <?= e((string)$line['symbol']) ?></td><td><?= e((string)$line['received']) ?></td><td><?= number_format(max(0,(float)$line['cantidadSolicitada']-(float)$line['received']),3,',','.') ?></td><td>$ <?= number_format((float)$line['precioUnitario'],2,',','.') ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php if($open && Authorization::can($u,'suppliers.receive')): ?><form class="inventory-form" action="action.php" method="post"><input type="hidden" name="csrf_token" value="<?= e(Csrf::token()) ?>"><input type="hidden" name="action" value="receive"><input type="hidden" name="idRemitoProveedor" value="<?= $id ?>"><section class="form-section"><div class="form-section-heading"><span>01</span><div><h3>Registrar recepción</h3><p>Indicá cantidades recibidas ahora; dejá 0 en las demás.</p></div></div><div class="form-grid"><div class="field"><label for="warehouse">Depósito *</label><select id="warehouse" name="idWarehouse" required><option value="">Seleccionar</option><?php foreach($warehouses as $w): ?><option value="<?= (int)$w['idWarehouse'] ?>"><?= e((string)$w['name']) ?></option><?php endforeach; ?></select></div><div class="field form-field-wide"><label for="note">Observaciones</label><textarea id="note" name="observaciones" maxlength="500" rows="2"></textarea></div></div><div class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th>Producto</th><th>Pendiente</th><th>Recibido ahora</th></tr></thead><tbody><?php foreach($lines as $line): $remaining=max(0,round((float)$line['cantidadSolicitada']-(float)$line['received'],3)); if($remaining<=0)continue; ?><tr><td><?= e((string)$line['name']) ?></td><td><?= number_format($remaining,3,',','.') ?> <?= e((string)$line['symbol']) ?></td><td><input type="number" name="received[<?= (int)$line['idProducto'] ?>]" min="0" max="<?= $remaining ?>" step="<?= (int)$line['allowsDecimals']?'0.001':'1' ?>" value="0"></td></tr><?php endforeach; ?></tbody></table></div></section><div class="form-footer"><button class="button button-primary">Confirmar recepción y actualizar stock</button></div></form><?php endif; ?>
<?php if($open && !$receipts && Authorization::can($u,'suppliers.manage')): ?><form method="post" action="action.php" class="form-footer" onsubmit="return confirm('¿Cancelar este remito sin recepciones?')"><input type="hidden" name="csrf_token" value="<?= e(Csrf::token()) ?>"><input type="hidden" name="action" value="cancel"><input type="hidden" name="idRemitoProveedor" value="<?= $id ?>"><button class="button button-danger">Cancelar remito</button></form><?php endif; ?>
<section class="inventory-panel"><div class="panel-title-row"><div><h3>Historial de recepciones</h3></div></div><?php if(!$receipts): ?><div class="table-empty"><p>No se registraron recepciones.</p></div><?php else: ?><div class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th>Recepción</th><th>Fecha</th><th>Depósito</th><th>Producto</th><th>Cantidad</th><th>Usuario</th><th>Observaciones</th></tr></thead><tbody><?php foreach($receipts as $receipt): ?><tr><td>#<?= (int)$receipt['idRecepcion'] ?></td><td><?= e((string)$receipt['fechaRecepcion']) ?></td><td><?= e((string)$receipt['warehouseName']) ?></td><td><?= e((string)$receipt['productName']) ?></td><td><?= e((string)$receipt['cantidadRecibida']) ?> <?= e((string)$receipt['symbol']) ?></td><td>#<?= (int)$receipt['actorUserId'] ?></td><td><?= e((string)($receipt['observaciones']??'')) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php SupplierPage::end(); ?>
