<?php
declare(strict_types=1);require dirname(__DIR__,2).'/src/bootstrap.php';
use Sedema\Payments\PaymentContext;use Sedema\Payments\PaymentPage;
$c=PaymentContext::boot();$user=$c['user'];$repo=$c['repository'];$db=$repo->db();
$search=mb_substr(trim((string)($_GET['search']??'')),0,100);$params=[];$where='';if($search!==''){$where='WHERE c.nombre LIKE ? OR c.apellido LIKE ? OR c.cuitDNI LIKE ?';$like='%'.$search.'%';$params=[$like,$like,$like];}
$st=$db->prepare("SELECT c.idCliente,c.nombre,c.apellido,c.cuitDNI,c.tipoCliente,COALESCE(SUM(CASE WHEN m.movementType='DEBITO' THEN m.amount ELSE -m.amount END),0) saldo FROM cliente c LEFT JOIN current_account_movement m ON m.idCliente=c.idCliente $where GROUP BY c.idCliente ORDER BY c.apellido,c.nombre LIMIT 250");$st->execute($params);$rows=$st->fetchAll();
$clientId=max(0,(int)($_GET['client']??0));$selected=null;$movements=[];if($clientId>0){$st=$db->prepare('SELECT idCliente,nombre,apellido,cuitDNI,tipoCliente FROM cliente WHERE idCliente=? LIMIT 1');$st->execute([$clientId]);$selected=$st->fetch()?:null;if($selected)$movements=$repo->currentAccountMovements($clientId);}
PaymentPage::begin('Cuenta corriente','account',$user);
?>
<section class="inventory-heading"><div><p class="section-kicker">Clientes</p><h2>Cuenta corriente</h2><p>Consulta de saldos y movimientos de pedidos imputados a cuenta corriente.</p></div></section>
<form class="inventory-toolbar" method="get"><div class="toolbar-search field"><label>Buscar cliente</label><input name="search" value="<?=e($search)?>" placeholder="Nombre o DNI/CUIT"></div><button class="button button-primary button-filter">Aplicar</button></form>
<section class="inventory-panel"><div class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th>Cliente</th><th>DNI/CUIT</th><th>Tipo</th><th>Saldo</th><th></th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="5">No hay clientes para mostrar.</td></tr><?php endif;?><?php foreach($rows as $r):?><tr><td><strong><?=e($r['apellido'].', '.$r['nombre'])?></strong></td><td><?=e((string)$r['cuitDNI'])?></td><td><?=e((string)$r['tipoCliente'])?></td><td><strong>$<?=number_format((float)$r['saldo'],2,',','.')?></strong></td><td><a class="table-link" href="current-account.php?client=<?=(int)$r['idCliente']?>">Ver movimientos</a></td></tr><?php endforeach;?></tbody></table></div></section>
<?php if($selected):?><section class="inventory-panel" style="margin-top:20px"><div class="panel-title-row"><div><h3><?=e($selected['apellido'].', '.$selected['nombre'])?></h3><p>Movimientos de cuenta corriente</p></div><a class="table-link" href="current-account.php">Cerrar detalle</a></div><div class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th>Fecha</th><th>Tipo</th><th>Pedido</th><th>Importe</th><th>Descripción</th></tr></thead><tbody><?php if(!$movements):?><tr><td colspan="5">No hay movimientos registrados.</td></tr><?php endif;?><?php foreach($movements as $m):?><tr><td><?=e((string)$m['createdAt'])?></td><td><?=e((string)$m['movementType'])?></td><td><?=!empty($m['idPedido'])?'#'.(int)$m['idPedido']:'—'?></td><td>$<?=number_format((float)$m['amount'],2,',','.')?></td><td><?=e((string)($m['description']??'—'))?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<?php PaymentPage::end(); ?>
