<?php
declare(strict_types=1);require dirname(__DIR__,2).'/src/bootstrap.php';
use Sedema\Authorization;use Sedema\Csrf;use Sedema\Payments\PaymentContext;use Sedema\Payments\PaymentPage;use Sedema\Payments\PaymentService;
$c=PaymentContext::boot();$user=$c['user'];$repo=$c['repository'];$gateway=$c['gateway'];Authorization::require($user,'payments.view');$id=max(0,(int)($_GET['id']??0));$p=$repo->payment($id);if(!$p){http_response_code(404);exit('El cobro no existe.');}$isAccount=(string)($p['tipoOperacion']??'PAGO')==='CUENTA_CORRIENTE';PaymentPage::begin('Cobro #'.$id,'payments',$user);
?>
<section class="inventory-heading compact-heading"><div><p class="section-kicker">Comprobante de cobro</p><h2>Cobro #<?=$id?></h2><p>Pedido #<?=(int)$p['idPedido']?> · <?=e($p['apellido'].', '.$p['nombre'])?></p></div><a class="back-button" href="collect.php?id=<?=(int)$p['idPedido']?>">← Volver al pedido</a></section>
<section class="inventory-panel"><div class="payment-receipt">
<div><span>Operación</span><strong><?=e(PaymentService::paymentLabel($p))?></strong></div><div><span>Importe</span><strong>$<?=number_format((float)$p['importe'],2,',','.')?></strong></div><div><span>Estado</span><strong><?=e((string)$p['estadoPago'])?></strong></div><div><span>Fecha</span><strong><?=e((string)$p['fechaPago'])?></strong></div>
<?php if(isset($p['importeBase']) && $p['importeBase']!==null):?><div><span>Importe base</span><strong>$<?=number_format((float)$p['importeBase'],2,',','.')?></strong></div><?php endif;?>
<?php if(!empty($p['adjustmentType'])):?><div><span>Ajuste</span><strong><?=e((string)$p['adjustmentType'])?> <?=number_format((float)$p['adjustmentPercent'],2,',','.')?>% ($<?=number_format((float)$p['adjustmentAmount'],2,',','.')?>)</strong></div><?php endif;?>
<?php if((string)$p['medioPago']==='EFECTIVO' && $p['cashReceived']!==null):?><div><span>Efectivo recibido</span><strong>$<?=number_format((float)$p['cashReceived'],2,',','.')?></strong></div><div><span>Vuelto</span><strong>$<?=number_format((float)$p['cashChange'],2,',','.')?></strong></div><?php endif;?>
<?php if((string)$p['medioPago']==='CHEQUE'):?><div><span>Banco</span><strong><?=e((string)$p['checkBank'])?></strong></div><div><span>Nº cheque</span><strong><?=e((string)$p['checkNumber'])?></strong></div><div><span>Titular</span><strong><?=e((string)$p['checkHolder'])?></strong></div><div><span>Vencimiento</span><strong><?=e((string)$p['checkDueDate'])?></strong></div><?php endif;?>
<?php if($isAccount):?><div><span>Cuenta corriente</span><strong>Imputación registrada</strong></div><?php endif;?>
</div>

<?php if((string)$p['estadoPago']==='PENDIENTE' && in_array((string)$p['medioPago'],['TARJETA','TRANSFERENCIA'],true)):?><div class="payment-gateway-box"><h3>Solicitud electrónica pendiente</h3><p>Medio: <strong><?=e(PaymentService::methodLabel((string)$p['medioPago']))?></strong></p><p>Referencia: <strong><?=e((string)($p['externalId']??$p['transaccionExternaID']))?></strong></p><?php if(!empty($p['qrImageUrl'])):?><img class="payment-qr" src="<?=e((string)$p['qrImageUrl'])?>" alt="Código QR de pago"><?php elseif(!empty($p['qrPayload'])):?><div class="payment-qr-payload"><span>Datos de solicitud / QR</span><code><?=e((string)$p['qrPayload'])?></code></div><?php endif;?><div class="form-actions"><?php if($gateway->mode()==='mock'&&Authorization::can($user,'payments.manage')):?><form method="post" action="action.php"><input type="hidden" name="csrf_token" value="<?=e(Csrf::token())?>"><input type="hidden" name="action" value="mock-approve"><input type="hidden" name="idPago" value="<?=$id?>"><button class="button button-primary">Simular aprobación</button></form><?php endif;?><form method="post" action="action.php"><input type="hidden" name="csrf_token" value="<?=e(Csrf::token())?>"><input type="hidden" name="action" value="verify"><input type="hidden" name="idPago" value="<?=$id?>"><button class="button button-secondary">Verificar estado</button></form></div></div><?php endif;?>

<?php if((string)$p['estadoPago']==='PENDIENTE' && (string)$p['medioPago']==='CHEQUE' && Authorization::can($user,'payments.manage')):?><div class="payment-gateway-box"><h3>Cheque pendiente de validación</h3><p>Confirmá el cheque cuando haya sido validado o rechazalo si no corresponde.</p><div class="form-actions"><form method="post" action="action.php"><input type="hidden" name="csrf_token" value="<?=e(Csrf::token())?>"><input type="hidden" name="action" value="approve-check"><input type="hidden" name="idPago" value="<?=$id?>"><button class="button button-primary">Aprobar cheque</button></form><form method="post" action="action.php" onsubmit="return confirm('¿Rechazar este cheque?')"><input type="hidden" name="csrf_token" value="<?=e(Csrf::token())?>"><input type="hidden" name="action" value="reject-check"><input type="hidden" name="idPago" value="<?=$id?>"><button class="button button-danger">Rechazar cheque</button></form></div></div><?php endif;?>
</section>
<div class="form-actions no-print"><button class="button button-secondary" onclick="window.print()">Imprimir comprobante</button></div>
<?php PaymentPage::end(); ?>
